# Build info for CapazOS

build_version = 0.8.3
build_date = 2026-02-04
build_environment = macOS Xcode

kernel_version=0.1.2
kernel_build_number = 1926
kernel_platform = aarch64
kernel_machine = Virt

core_version = 0.8.5
core_name = Capaz
