# Build info for CapazOS

build_version = 0.8.7
build_date = 2026-02-05
build_environment = macOS Xcode

kernel_version=0.2.1
kernel_build_number = 1985
kernel_machine=virt

core_version = 0.9.6
core_name = Capaz
