# Build info for CapazOS

build_version = 0.8.1
build_date = 2026-02-03
build_environment = macOS Xcode

kernel_version=0.1.0
kernel_build_number = 1818
kernel_platform = aarch64
kernel_machine = Virt

core_version = 0.8.1
core_name = Capaz
